steps update

diff --git a/.github/workflows/consensus-checks.yaml b/.github/workflows/consensus-checks.yaml
--- a/.github/workflows/consensus-checks.yaml
+++ b/.github/workflows/consensus-checks.yaml
@@ -12,6 +12,8 @@ env:
   GOPROXY: https://proxy.golang.org,https://gocenter.io,direct
   CORE_PATH: /home/runner/work/assured-ledger/assured-ledger/ledger-core
   ACR_HOST: usciregistry.azurecr.io
+  PROMETHEUS_USER: ${{secrets.PROMETHEUS_USER}}
+  PROMETHEUS_PASS: ${{secrets.PROMETHEUS_PASS}}
 jobs:
   prepare:
     name: prepare # don't change, this name is used in repository restricts!
@@ -44,33 +46,48 @@ jobs:
         run: |
           echo "::set-env name=INSOLAR_TAG::${GITHUB_SHA:0:8}"
           echo "::set-env name=INSOLAR_NETWORK_SIZE::aks-10node"
-          echo "::set-env name=INSOLAR_NAMESPACE::${GITHUB_SHA:0:8}${GITHUB_RUN_ID}"
-          echo "::set-env name=INSOLAR_UPTIME::3000"
-      - name: copy docker auth secret
+          echo "::set-env name=INSOLAR_NAMESPACE::${GITHUB_SHA:0:8}-${GITHUB_RUN_ID}"
+          echo "::set-env name=INSOLAR_DESIRED_UPTIME::300"
+      - name: Preparation - copy docker auth secret
         run: |
           docker login $ACR_HOST --username ${{secrets.ACR_SP_ID}} --password ${{secrets.ACR_SP_SECRET}}
           cp /home/runner/.docker/config.json ledger-core/scripts/deploy/kube/gitops/dockerconfigjson
-      - name: save kubeconfig
+      - name: Preparation - save kubeconfig
         run: echo "${{secrets.CLOUD_KUBECONFIG}}" >> aks.yaml
-      - name: github token
+      - name: Praparation - github token for gitops access
         run: git config --global url."https://${{secrets.INS_SERVICE_PAT}}@github.com/".insteadOf "https://github.com/"
-      - name: run network
+      - name: Ingress access check (IF THIS STEP FAILED - CALL DEVOPS, RED ALERT)
+        run:  curl -s "https://$PROMETHEUS_USER:$PROMETHEUS_PASS@prometheus.uscifarm.insolar.io/prometheus/api/v1/labels" | jq -r '.status'
+      - name: Deploy network
         run: kubectl kustomize ledger-core/scripts/deploy/kube/gitops | envsubst '${INSOLAR_NAMESPACE} ${INSOLAR_TAG} ${INSOLAR_NETWORK_SIZE}' | kubectl -n $INSOLAR_NAMESPACE apply -f -
-      - name: wait for successfull rollout
+      - name: Rollout check (IF THIS STEP FAILED - CALL DEV/OPS, YELLOW ALERT)
         run: kubectl -n $INSOLAR_NAMESPACE rollout status sts/virtual --timeout=300s
-      - name: pulsewatcher
+      - name: Pulsewatcher network check (IF THIS STEP FAILED - CALL DEV, READ LOGS YELLOW ALERT)
         run: |
-          for try in {0..100}; do
+          for attempt in {0..100}; do
             if kubectl -n $INSOLAR_NAMESPACE exec -i deploy/pulsewatcher -- bash -c 'pulsewatcher -c /etc/pulsewatcher/pulsewatcher.yaml -s' | grep 'READY' | grep -v 'NOT'; then
               echo "network ready!"; exit 0
+            elif [ "$attempt" -eq 100 ]; then
+              echo "number of attempts exceeded"
+              exit 1
             else echo -n '.'; sleep 5
             fi
           done
-      - name: wait and gather data
-        run:  sleep $INSOLAR_UPTIME
-      - name: gather metrics
+      - name: Set network start time variable
+        run:  echo "::set-env name=INSOLAR_START_TIME::$(date +'%s)"
+      - name: Keep network running for a desired period of time
+        run:  sleep $INSOLAR_DESIRED_UPTIME
+      - name: Grab utility binaries
         run: |
-          wget -q https://github.com/insolar/consensus-reports/releases/download/v1.0.2/{report,metricreplicator}
+          wget -q https://github.com/insolar/consensus-reports/releases/download/v1.0.2/{report,metricreplicator} -P bin/
+          chmod +x bin/{report,metricreplicator}
+#     - name: gather metrics and generate report (IF THIS STEP FAILED - CALL DEV, READ LOGS BLUE ALERT)
+#       run:  todo
+      - name: Provide link to grafana
+        run:  echo "https://monitoring.uscifarm.insolar.io/d/LmD-fXFZz/ins-network?orgId=1&refresh=10s&var-phase=All&var-packetType=All&var-namespace=$INSOLAR_NAMESPACE&from=now-10m&to=now"
+      - name: mandatory debug
+        if: always()
+        run: kubectl get all --all-namespaces
       - name: cleanup
         if: always()
         run: kubectl delete ns $INSOLAR_NAMESPACE --ignore-not-found=true
